name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./03-app-dotnet
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Verify Directory Change
      run: pwd
    - name: List files
      run: ls
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal    
    - name: Run the Publish
      run: dotnet publish --configuration Release --no-restore --output ./publish
    - name: zip publish
      run: Compress-Archive -Path ./publish -DestinationPath ./publish/publish.zip
